language: java

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

jdk:
  - openjdk11

cache:
  - directories:
      - $HOME/.m2

before_install:
  - pip install --user awscli


before_script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRECT_ACCESS_KEY
  - aws configure set region eu-west-1
  - aws configure set output json

script:
  - mvn -B clean compile assembly:assembly -DdescriptorId=jar-with-dependencies



deploy:
  provider: script
  script: aws lambda update-function --function-name 'ASCKLambda' --zip-file 'fileb://target/asck-alexa-skill-jar-with-dependencies.jar'
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_failure: always