language: java

jdk:
  - openjdk11

cache:
  - directories:
      - $HOME/.m2

script:
  - mvn clean package -B

deploy:
  provider: lambda
  function_name: ASCKLambda
  region: eu-west-1
  role: arn:aws:iam::470183980790:role/service-role/ASCKLambda-role-ajfuk4b4
  runtime: java8
  handler_name: handleRequest
  module_name: org.asckteam.alexa.skill.ASCKStreamHandler